name = "rsw"
version = "0.0.1"
# default `50` ms
interval = 50

# ---------------------------

# rsw new my-wasm
[new]
use = true
dir = ""

# ---------------------------

# package: rsw-foo
[[crates]]
# default `.`
root = "."
# npm package name
name = "rsw-foo"
# default `pkg`
out-dir = "mypkg"
[crates.watch]
# default `true`
run = false
# profile: `dev` | `profiling`, defalut `dev`
profile = "dev"
[crates.build]
run = false
# profile: `release` | `profiling`, default `release`
profile = "profiling"

# ---------------------------

# package: @rsw/bar
[[crates]]
name = "@rsw/bar"
