name = 'rsw'
version = "0.0.1"
interval = 50

[[crates]]
root = "."
name = "rsw-foo"
# out-dir = "./mypkg"
# profile: dev | profiling, defalut `dev`
[crates.watch]
run = true
profile = "dev"
# profile: release | profiling, default `release`
[crates.build]
run = false
profile = "profiling"

[[crates]]
name = "@rsw/bar"
